/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf.grupo;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giuliano.sallin
 */
public class Servidor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Servidor.class.getName());
    private ArrayList<inf.grupo.Pessoa> lista = new ArrayList<>();

    /**
     * Creates new form Servidor
     */
    public Servidor() {
        initComponents();
        iniciarServidorThread();
    }

    private void iniciarServidorThread() {
        new Thread(() -> {
            try {
                int portaServidor = 50000;
                ServerSocket servidor = new ServerSocket(portaServidor);
                System.out.println("Servidor ouvindo a porta: " + portaServidor);

                while (true) {
                    Socket cliente = servidor.accept();
                    System.out.println("Cliente conectado: " + cliente.getInetAddress());

                    // 1. IMPORTANTE: No Servidor, abra PRIMEIRO o InputStream para ler o que o cliente mandou
                    ObjectInputStream entrada = new ObjectInputStream(cliente.getInputStream());
                    String nomePessoa = (String) entrada.readObject();

                    // 2. Gerar o e-mail
                    String[] vetorNome = nomePessoa.trim().split("\\s+");
                    String email = "";
                    if (vetorNome.length > 1) {
                        email = vetorNome[0] + "." + vetorNome[vetorNome.length - 1] + "@ufn.edu.br";
                    } else {
                        email = vetorNome[0] + "@ufn.edu.br";
                    }

                    nomePessoa = nomePessoa.toUpperCase();
                    email = email.toLowerCase();

                    inf.grupo.Pessoa p = new inf.grupo.Pessoa(nomePessoa, email);

                    boolean encontrado = false;

                    // 3. Verificar duplicidade na lista de forma segura (synchronized)
                    synchronized (lista) {
                        if (lista.contains(p)) {
                            encontrado = true;
                        } else {
                            lista.add(p);
                            // Ordenar a lista alfabeticamente pelo nome
                            lista.sort(Comparator.comparing(inf.grupo.Pessoa::getNome));
                        }
                    }

                    // 4. DEPOIS de ler a entrada, abra o OutputStream para enviar a resposta
                    ObjectOutputStream saida = new ObjectOutputStream(cliente.getOutputStream());
                    saida.flush();

                    if (!encontrado) {
                        saida.writeObject(p);
                    } else {
                        saida.writeObject(null); // Envia null se já estiver cadastrado
                    }
                    saida.flush();

                    // Fechar os recursos deste cliente
                    entrada.close();
                    saida.close();
                    cliente.close();

                    // 5. Atualizar a JTable na interface gráfica do Servidor
                    javax.swing.SwingUtilities.invokeLater(this::atualizarTabela);

                    System.out.println("Processado com sucesso para: " + nomePessoa);
                }
            } catch (IOException | ClassNotFoundException e) {
                System.out.println("Erro crítico no Servidor: " + e.getMessage());
                e.printStackTrace();
            }
        }).start();
    }

    private void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        for (inf.grupo.Pessoa p : lista) {
            modelo.addRow(new Object[]{p.getNome(), p.getEmail()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Usuários Cadastrados");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "E-Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblTitulo)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Servidor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
